# -*- coding: utf-8 -*-
"""USADOPipelineComum_refatorado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQr1TcA2Z5RfkHqRQvtNox2Aff1WEZ99
"""

from google.colab import drive
drive.mount('/content/drive')

"""# **Bibliotecas**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from dataclasses import dataclass, asdict
from typing import Any, Dict, List, Optional, Tuple

from IPython.display import HTML, display

"""# **Carregar a base**"""

df = pd.read_csv("/content/drive/MyDrive/Dissertacao/EstudoCaso/Base depressao_PUC.csv", sep=";")

df["sales_channel"] = df.pop("sales_channel")

"""# **Verificar tipo de atributo**"""

# =========================================================
# Funções auxiliares (robustas a missing) e relatório
# =========================================================

def _non_null(series: pd.Series) -> pd.Series:
    """Retorna apenas valores não-nulos."""
    return series.dropna()


def _n_unique_non_null(series: pd.Series) -> int:
    """Número de valores distintos desconsiderando ausências."""
    return int(_non_null(series).nunique())


def _is_numeric(series: pd.Series) -> bool:
    """Indica se a série é numérica (dtype numérico)."""
    return pd.api.types.is_numeric_dtype(series)


def _is_dichotomous(series: pd.Series) -> bool:
    """Indica se a série possui exatamente 2 valores distintos (não-nulos)."""
    return _n_unique_non_null(series) == 2


def _is_discrete_numeric(series: pd.Series) -> bool:
    """Considera discreto se todos os valores não-nulos forem inteiros.

    Observação: lida com o caso de colunas inteiras com missing, que podem ser
    convertidas para float pelo pandas.
    """
    if not _is_numeric(series):
        return False

    x = _non_null(series)
    if x.empty:
        return False

    x = x.astype(float)
    return bool(np.isclose(x % 1, 0.0, atol=1e-12).all())


def _min_max(series: pd.Series) -> Tuple[Optional[float], Optional[float]]:
    """Retorna (min, max) para séries numéricas; caso contrário, (None, None)."""
    x = _non_null(series)
    if x.empty or (not _is_numeric(series)):
        return None, None
    return float(x.min()), float(x.max())


def _levels(series: pd.Series, max_levels: int = 30) -> str:
    """Lista valores distintos (até max_levels), útil para exibir opções de resposta."""
    x = _non_null(series)
    if x.empty:
        return ""

    vals = list(pd.unique(x))
    try:
        vals = sorted(vals)
    except Exception:
        pass

    if len(vals) > max_levels:
        return ", ".join(map(str, vals[:max_levels])) + f", ... (+{len(vals) - max_levels})"
    return ", ".join(map(str, vals))


def _bold(text: str) -> str:
    return f"**{text}**"


def _red(html_text: str) -> str:
    # Renderiza em HTML (Jupyter/Colab)
    return f"<span style='color:#d62728; font-weight:600'>{html_text}</span>"


def format_attr_name(data: pd.DataFrame, col: str) -> str:
    """Formata o nome do atributo em negrito e destaca cardinalidade 1 em vermelho."""
    nunq = _n_unique_non_null(data[col])
    name = _bold(col)
    if nunq == 1:
        name = _red(name)
    return name


def _to_html(df_: pd.DataFrame) -> str:
    return df_.to_html(index=False, escape=False)


def _section(title: str) -> None:
    display(HTML(f"<h4 style='margin:14px 0 6px 0'>{title}</h4>"))


def _tipo_atributo(series: pd.Series) -> str:
    """Tipagem simples para relatório (inclui atributo classe)."""
    nunq = _n_unique_non_null(series)
    if nunq == 0:
        return "Vazio"

    if _is_numeric(series):
        if nunq == 2:
            return "Dicotômico numérico"
        return "Numérico discreto" if _is_discrete_numeric(series) else "Numérico contínuo"

    if nunq == 2:
        return "Dicotômico nominal"
    return "Categórico nominal"


def to_html_com_titulo(df_: pd.DataFrame, titulo: str) -> str:
    """Converte um DataFrame para HTML e insere um caption no topo."""
    html = df_.to_html(index=False, escape=False)
    return html.replace(
        '<table border="1" class="dataframe">',
        '<table border="1" class="dataframe">'
        "<caption style='caption-side:top; font-weight:600; text-align:left'>"
        f"{titulo}</caption>",
    )


# =========================================================
# Função principal
# =========================================================

def gerar_relatorio(data: pd.DataFrame, target_col: Optional[str] = None) -> Dict[str, Any]:
    """Gera tabelas (e versões HTML) para caracterização de atributos.

    - Assume, por padrão, que a classe é a última coluna.
    - Não altera o DataFrame de entrada.
    """
    if target_col is None:
        target_col = data.columns[-1]

    target_exists = target_col in data.columns
    input_cols = [c for c in data.columns if c != target_col]

    # -------------------------
    # Tabela 1 — Resumo (somente ENTRADA)
    # -------------------------
    n_inst = len(data)
    missing_cells = int(data.isna().sum().sum())
    total_cells = int(data.shape[0] * data.shape[1])
    missing_pct = (missing_cells / total_cells) * 100 if total_cells else 0.0

    qtd_dicot = 0
    qtd_num_disc = 0
    qtd_num_cont = 0
    qtd_cat_nom = 0

    # -------------------------
    # Tabela 3/4/5 — Detalhes (ENTRADA)
    # -------------------------
    tab_dicot: List[Dict[str, Any]] = []
    tab_nom: List[Dict[str, Any]] = []
    tab_num: List[Dict[str, Any]] = []

    for col in input_cols:
        s = data[col]
        nunq = _n_unique_non_null(s)
        if nunq == 0:
            continue

        nome = format_attr_name(data, col)

        # Dicotômico
        if _is_dichotomous(s):
            qtd_dicot += 1
            tab_dicot.append({
                "Atributo": nome,
                "Forma": "numérico" if _is_numeric(s) else "nominal",
                "Opções de resposta": _levels(s),
            })
            continue

        # Numérico (não dicotômico)
        if _is_numeric(s):
            if _is_discrete_numeric(s):
                qtd_num_disc += 1
                tipo = "Discreto"
            else:
                qtd_num_cont += 1
                tipo = "Contínuo"

            vmin, vmax = _min_max(s)
            tab_num.append({
                "Atributo": nome,
                "Tipo": tipo,
                "min": vmin,
                "max": vmax,
            })
            continue

        # Categórico nominal (não dicotômico)
        qtd_cat_nom += 1
        tab_nom.append({
            "Atributo": nome,
            "Cardinalidade": nunq,
            "Opções de resposta": _levels(s),
        })

    resumo = pd.DataFrame([
        {
            "Instâncias": n_inst,
            "Dados ausentes (células)": missing_cells,
            "Dados ausentes (%)": round(missing_pct, 4),
            "Discretos": qtd_num_disc,
            "Contínuos": qtd_num_cont,
            "Dicotômicos": qtd_dicot,
            "Categóricos nominais": qtd_cat_nom,
            "Atributos de entrada": len(input_cols),
        }
    ])

    # -------------------------
    # Tabela 2 — Classe
    # -------------------------
    if target_exists:
        s_y = data[target_col]
        classe_info = pd.DataFrame([
            {
                "Classe": _bold(target_col),
                "Tipo de atributo": _tipo_atributo(s_y),
                "Quantidade de respostas": _n_unique_non_null(s_y),
            }
        ])
    else:
        classe_info = pd.DataFrame([
            {
                "Classe": _bold(str(target_col)),
                "Tipo de atributo": "Não encontrada",
                "Quantidade de respostas": 0,
            }
        ])

    df_dicot = pd.DataFrame(tab_dicot)
    df_nom = pd.DataFrame(tab_nom)
    df_num = pd.DataFrame(tab_num)

    return {
        "tabela_resumo": resumo,
        "tabela_dicotomicos": df_dicot,
        "tabela_nominais": df_nom,
        "tabela_numericos": df_num,
        "tabela_classe": classe_info,
        "html_resumo": to_html_com_titulo(resumo, "Tabela 1 — Resumo geral da base de dados"),
        "html_classe": to_html_com_titulo(classe_info, "Tabela 2 — Caracterização do atributo classe"),
        "html_dicotomicos": to_html_com_titulo(df_dicot, "Tabela 3 — Atributos dicotômicos de entrada"),
        "html_nominais": to_html_com_titulo(df_nom, "Tabela 4 — Atributos categóricos nominais de entrada"),
        "html_numericos": to_html_com_titulo(df_num, "Tabela 5 — Atributos numéricos de entrada"),
    }


# =========================================================
# Uso (base já carregada)
# =========================================================
rel = gerar_relatorio(df)  # assume classe = última coluna

display(HTML(rel["html_resumo"]))
display(HTML(rel["html_classe"]))
display(HTML(rel["html_dicotomicos"]))
display(HTML(rel["html_nominais"]))
display(HTML(rel["html_numericos"]))

# Converte células vazias ou contendo apenas espaços em NaN
df = df.replace(r'^\s*$', np.nan, regex=True)

# Quantidade de ausentes por coluna
ausentes = df.isna().sum()

# Percentual de ausentes por coluna
percentual = (df.isna().mean() * 100).round(2)

# Tabela final
relatorio_ausentes = pd.DataFrame({
    "Coluna": df.columns,
    "Qtd_Ausentes": ausentes.values,
    "Percentual_Ausentes": percentual.values
})

# Mostrar apenas colunas que possuem ausentes
relatorio_ausentes = relatorio_ausentes[
    relatorio_ausentes["Qtd_Ausentes"] > 0
]

# Ordenar da maior para a menor quantidade de ausentes
relatorio_ausentes = relatorio_ausentes.sort_values(
    "Qtd_Ausentes",
    ascending=False
)

print(relatorio_ausentes.to_string(index=False))

"""# **Ausência, redundancia e inconsistencia**"""

# =========================================
# CONFIGURAÇÃO
# =========================================
# CLASSE = ÚLTIMA COLUNA

y_col = df.columns[-1]
id_cols: List[str] = [

'Id',
'CDI1_T1', 'CDI2_T1', 'CDI3_T1', 'CDI4_T1', 'CDI5_T1', 'CDI6_T1',
'CDI7_T1', 'CDI8_T1', 'CDI9_T1', 'CDI10_T1', 'CDI11_T1', 'CDI12_T1',
'CDI13_T1', 'CDI14_T1', 'CDI15_T1', 'CDI16_T1', 'CDI17_T1', 'CDI18_T1',
'CDI19_T1', 'CDI20_T1', 'CDI21_T1', 'CDI22_T1', 'CDI23_T1', 'CDI24_T1',
'CDI25_T1', 'CDI26_T1', 'CDI27_T1',
    ]  # opcional (ex.: ["Patient ID"])


# =========================================
# 1) Atributos com ausência e quantidade
# =========================================
missing_by_attr = df.isna().sum()
missing_by_attr = missing_by_attr[missing_by_attr > 0].sort_values(ascending=False)

missing_by_attr_df = (
    missing_by_attr.to_frame(name="Qtd ausente")
    .reset_index()
    .rename(columns={"index": "Atributo"})
)

if not missing_by_attr_df.empty:
    missing_by_attr_df["Atributo"] = missing_by_attr_df["Atributo"].apply(lambda c: format_attr_name(df, c))


# =========================================
# 2) Instâncias com ausência e quantidade (índice iniciando em 1)
# =========================================
missing_by_row = df.isna().sum(axis=1)
rows_with_missing = missing_by_row[missing_by_row > 0].sort_values(ascending=False)

missing_by_row_df = (
    rows_with_missing.to_frame(name="Qtd ausente")
    .reset_index()
    .rename(columns={"index": "Índice da instância"})
)

if not missing_by_row_df.empty:
    missing_by_row_df["Índice da instância"] = missing_by_row_df["Índice da instância"] + 1


# =========================================
# 3) Instâncias redundantes (duplicadas) (índices iniciando em 1)
# =========================================
cols_for_dupe = [c for c in df.columns if c not in id_cols]
dup_mask = df.duplicated(subset=cols_for_dupe, keep=False)

duplicated_groups_df = pd.DataFrame()
if dup_mask.any():
    tmp = df.loc[dup_mask, cols_for_dupe].copy()
    tmp["__idx__"] = df.index[dup_mask]  # base 0

    duplicated_groups_df = (
        tmp.groupby(cols_for_dupe, dropna=False)["__idx__"]
        .apply(list)
        .reset_index(name="Índices das instâncias")
    )
    duplicated_groups_df["Índices das instâncias"] = (
        duplicated_groups_df["Índices das instâncias"].apply(lambda lst: [i + 1 for i in lst])
    )
    duplicated_groups_df["Contagem"] = duplicated_groups_df["Índices das instâncias"].apply(len)
    duplicated_groups_df = duplicated_groups_df.sort_values("Contagem", ascending=False).reset_index(drop=True)

    # resumo compacto
    duplicated_groups_df = duplicated_groups_df[["Contagem", "Índices das instâncias"]]


# =========================================
# 4) Instâncias inconsistentes (mesmas entradas -> classe diferente)
#     (robusta a NaN nas features; índices iniciando em 1)
# =========================================
feature_cols = [c for c in df.columns if c not in (id_cols + [y_col])]

inconsistencies_df = pd.DataFrame()
inconsistency_index_groups_df = pd.DataFrame()

if len(feature_cols) == 0:
    inconsistencies_df = pd.DataFrame({"Mensagem": ["Não há colunas de entrada suficientes (feature_cols vazio)."]})
else:
    nunique_target = df.groupby(feature_cols, dropna=False)[y_col].nunique(dropna=True)

    inconsistent_keys_df = (
        nunique_target[nunique_target > 1]
        .reset_index()[feature_cols]
    )

    if inconsistent_keys_df.empty:
        inconsistencies_df = pd.DataFrame({
            "Mensagem": ["Nenhuma inconsistência encontrada (mesmas entradas e classe diferente)."]
        })
    else:
        aux = df.copy()
        aux["__idx__"] = aux.index  # base 0

        inconsistent_rows = aux.merge(inconsistent_keys_df, on=feature_cols, how="inner")

        inconsistencies_df = (
            inconsistent_rows.groupby(feature_cols, dropna=False)[y_col]
            .apply(lambda s: sorted(pd.unique(s.dropna())))
            .reset_index(name=f"Valores distintos em {y_col}")
        )
        inconsistencies_df["Qtd valores distintos"] = inconsistencies_df[f"Valores distintos em {y_col}"].apply(len)

        inconsistency_index_groups_df = (
            inconsistent_rows.groupby(feature_cols, dropna=False)["__idx__"]
            .apply(list)
            .reset_index(name="Índices das instâncias")
        )
        inconsistency_index_groups_df["Índices das instâncias"] = (
            inconsistency_index_groups_df["Índices das instâncias"].apply(lambda lst: [i + 1 for i in lst])
        )
        inconsistency_index_groups_df["Contagem"] = inconsistency_index_groups_df["Índices das instâncias"].apply(len)
        inconsistency_index_groups_df = (
            inconsistency_index_groups_df.sort_values("Contagem", ascending=False)
            .reset_index(drop=True)
        )

        inconsistencies_df = inconsistencies_df[[f"Valores distintos em {y_col}", "Qtd valores distintos"]].head(50)
        inconsistency_index_groups_df = inconsistency_index_groups_df[["Contagem", "Índices das instâncias"]].head(50)


# =========================================
# 5) Visualização matricial da nulidade (presença vs ausência)
# =========================================
try:
    import missingno as msno

    ax = msno.matrix(df, figsize=(12, 4), sparkline=False)
    plt.title("Visualização matricial da nulidade (presença vs ausência)")
    plt.show()
except Exception:
    presence = (~df.isna()).astype(int).values
    plt.figure(figsize=(12, 4))
    plt.imshow(presence, aspect="auto", interpolation="nearest", cmap="gray")
    plt.xlabel("Atributos (colunas)")
    plt.ylabel("Instâncias (linhas)")
    plt.title("Visualização matricial da nulidade (1 = presente, 0 = ausente)")
    if df.shape[1] <= 40:
        plt.xticks(ticks=np.arange(df.shape[1]), labels=df.columns, rotation=45, ha="right", fontsize=8)
    plt.tight_layout()
    plt.show()


# =========================================
# 6) Proporção de balanceamento (classe = última coluna)
# =========================================
counts = df[y_col].value_counts(dropna=False)
balance_df = (
    counts.to_frame(name="Contagem")
    .assign(Proporção=lambda x: x["Contagem"] / x["Contagem"].sum())
    .reset_index()
    .rename(columns={"index": format_attr_name(df, y_col)})
)


# =========================================
# EXIBIÇÃO EM HTML
# =========================================
_section("Atributos com ausência (quantidade)")
if missing_by_attr_df.empty:
    display(HTML(_to_html(pd.DataFrame({"Mensagem": ["Nenhum atributo com ausência."]}))))
else:
    display(HTML(_to_html(missing_by_attr_df)))

_section("Instâncias com ausência (quantidade)")
if missing_by_row_df.empty:
    display(HTML(_to_html(pd.DataFrame({"Mensagem": ["Nenhuma instância com ausência."]}))))
else:
    display(HTML(_to_html(missing_by_row_df.head(200))))

_section("Instâncias redundantes (duplicadas)")
if duplicated_groups_df.empty:
    display(HTML(_to_html(pd.DataFrame({"Mensagem": ["Nenhuma redundância (linhas duplicadas) encontrada."]}))))
else:
    display(HTML(_to_html(duplicated_groups_df.head(50))))

if not inconsistency_index_groups_df.empty:
    _section("Índices das instâncias inconsistentes")
    display(HTML(_to_html(inconsistency_index_groups_df)))

_section(f"Proporção de balanceamento (classe = {y_col})")
display(HTML(_to_html(balance_df)))

"""# **Limpeza da base**"""

# ============================================================
# CONFIGURAÇÃO (OBRIGATÓRIA)
# ============================================================
base_name = "Depressao"        # nome da base original (sem .csv)
irrelevant_cols: List[str] = [

'Id',
'CDI1_T1', 'CDI2_T1', 'CDI3_T1', 'CDI4_T1', 'CDI5_T1', 'CDI6_T1',
'CDI7_T1', 'CDI8_T1', 'CDI9_T1', 'CDI10_T1', 'CDI11_T1', 'CDI12_T1',
'CDI13_T1', 'CDI14_T1', 'CDI15_T1', 'CDI16_T1', 'CDI17_T1', 'CDI18_T1',
'CDI19_T1', 'CDI20_T1', 'CDI21_T1', 'CDI22_T1', 'CDI23_T1', 'CDI24_T1',
'CDI25_T1', 'CDI26_T1', 'CDI27_T1',
    ]  # ex.: ["ID", "Timestamp"]
id_cols: List[str] = [0]           # opcional

missing_threshold = 0.40

# CLASSE = ÚLTIMA COLUNA DO DF ORIGINAL (NÃO MUDA)
y_col = df.columns[-1]


# ============================================================
# FUNÇÕES AUXILIARES ESPECÍFICAS
# ============================================================

def _safe_mode(series: pd.Series):
    s2 = series.dropna()
    return s2.mode(dropna=True).iloc[0] if not s2.empty else np.nan


# ============================================================
# CONTROLE DE REMOÇÕES (para relatório)
# ============================================================
removed_attrs: Dict[str, List[str]] = {
    "Irrelevantes (usuário)": [],
    "Cardinalidade = 1": [],
    f"> {int(missing_threshold * 100)}% de ausência": [],
}

removed_instances: Dict[str, List[int]] = {
    "Ausência da classe": [],
    "Redundância": [],
    "Inconsistência": [],
    f"> {int(missing_threshold * 100)}% de ausência": [],
}


# ============================================================
# PIPELINE DE LIMPEZA
# ============================================================

df_clean = df.copy()

# cria __idx__ SEM ALTERAR y_col
# (rastreamento das instâncias, em índice base 0; relatório será exibido em base 1)
df_clean["__idx__"] = np.arange(len(df_clean))


# ------------------------------------------------------------
# 1) Remover atributos irrelevantes (usuário)
# ------------------------------------------------------------
drop_cols_user = [c for c in irrelevant_cols if c in df_clean.columns and c != y_col]
removed_attrs["Irrelevantes (usuário)"] = drop_cols_user.copy()
df_clean = df_clean.drop(columns=drop_cols_user, errors="ignore")


# ------------------------------------------------------------
# 2) Remover atributos com cardinalidade = 1 (exceto classe)
# ------------------------------------------------------------
cardinality_1_cols = [
    c for c in df_clean.columns
    if c not in (y_col, "__idx__") and df_clean[c].dropna().nunique() == 1
]
removed_attrs["Cardinalidade = 1"] = cardinality_1_cols.copy()
df_clean = df_clean.drop(columns=cardinality_1_cols, errors="ignore")


# ------------------------------------------------------------
# 3) Remover instâncias com ausência da classe
# ------------------------------------------------------------
mask = df_clean[y_col].isna()
removed_instances["Ausência da classe"] = (df_clean.loc[mask, "__idx__"] + 1).tolist()
df_clean = df_clean.loc[~mask].copy()


# ------------------------------------------------------------
# 4) Remover redundâncias (duplicatas)
# ------------------------------------------------------------
dupe_subset = [c for c in df_clean.columns if c not in (id_cols + ["__idx__"])]
dup_mask = df_clean.duplicated(subset=dupe_subset, keep="first")
removed_instances["Redundância"] = (df_clean.loc[dup_mask, "__idx__"] + 1).tolist()
df_clean = df_clean.loc[~dup_mask].copy()


# ------------------------------------------------------------
# 5) Remover inconsistências (mesmas entradas → classe diferente)
#     Robusto a NaN: usa merge (não usa MultiIndex/.loc)
# ------------------------------------------------------------
feature_cols = [c for c in df_clean.columns if c not in (id_cols + [y_col, "__idx__"])]

if feature_cols:
    nunique_target = df_clean.groupby(feature_cols, dropna=False)[y_col].nunique(dropna=True)

    inconsistent_keys_df = (
        nunique_target[nunique_target > 1]
        .reset_index()[feature_cols]
    )

    if not inconsistent_keys_df.empty:
        marked = df_clean.merge(inconsistent_keys_df, on=feature_cols, how="inner")
        removed_instances["Inconsistência"] = (marked["__idx__"] + 1).tolist()

        bad_idx = set(marked["__idx__"].tolist())
        df_clean = df_clean.loc[~df_clean["__idx__"].isin(bad_idx)].copy()


# ------------------------------------------------------------
# 6) Remover atributos com > missing_threshold de ausência (exceto classe)
# ------------------------------------------------------------
missing_frac_cols = df_clean.isna().mean()
cols_drop_missing = [
    c for c, frac in missing_frac_cols.items()
    if c not in (y_col, "__idx__") and frac > missing_threshold
]
removed_attrs[f"> {int(missing_threshold * 100)}% de ausência"] = cols_drop_missing.copy()
df_clean = df_clean.drop(columns=cols_drop_missing, errors="ignore")


# ------------------------------------------------------------
# 7) Remover instâncias com > missing_threshold de ausência
# ------------------------------------------------------------
row_missing_frac = df_clean.isna().mean(axis=1)
mask = row_missing_frac > missing_threshold
removed_instances[f"> {int(missing_threshold * 100)}% de ausência"] = (df_clean.loc[mask, "__idx__"] + 1).tolist()
df_clean = df_clean.loc[~mask].copy()


# ------------------------------------------------------------
# 8) Imputação (média numéricos, moda nominais)
# ------------------------------------------------------------
num_cols = [
    c for c in df_clean.columns
    if c not in (y_col, "__idx__") and _is_numeric(df_clean[c])
]
cat_cols = [
    c for c in df_clean.columns
    if c not in (y_col, "__idx__") and c not in num_cols
]

for c in num_cols:
    df_clean[c] = df_clean[c].fillna(df_clean[c].mean(skipna=True))

for c in cat_cols:
    df_clean[c] = df_clean[c].fillna(_safe_mode(df_clean[c]))


# ------------------------------------------------------------
# 9) Salvar base final
# ------------------------------------------------------------
out_path = f"/content/drive/MyDrive/Dissertacao/EstudoCaso/{base_name}_Limpa.csv"

df_final = df_clean.drop(columns="__idx__").reset_index(drop=True)
df_final.to_csv(out_path, index=False)


# ============================================================
# RELATÓRIO FINAL (HTML)
# ============================================================
attrs_removed_df = pd.DataFrame([
    {"Motivo": k, "Atributos": ", ".join(v) if v else "-"}
    for k, v in removed_attrs.items()
])

inst_removed_df = pd.DataFrame([
    {"Motivo": k, "Índices das instâncias": ", ".join(map(str, v)) if v else "-"}
    for k, v in removed_instances.items()
])

remaining_nominal = [c for c in df_final.columns if c != y_col and not _is_numeric(df_final[c])]
nominal_df = pd.DataFrame({"Atributos nominais restantes para codificação": remaining_nominal})

balance_df = (
    df_final[y_col]
    .value_counts(dropna=False)
    .to_frame(name="Contagem")
    .assign(Proporção=lambda x: x["Contagem"] / x["Contagem"].sum())
    .reset_index()
    .rename(columns={"index": "Classe"})
)


# ============================================================
# CONTAGEM DOS TIPOS DE ATRIBUTOS RESTANTES (exceto classe)
# ============================================================
n_num_cont = 0
n_num_disc = 0
n_dicot_num = 0
n_dicot_nom = 0
n_nominal_nao_dicot = 0

for col in df_final.columns:
    if col == y_col:
        continue

    s = df_final[col]
    nunq = int(s.dropna().nunique())
    if nunq == 0:
        continue

    if _is_numeric(s):
        if nunq == 2:
            n_dicot_num += 1
        elif _is_discrete_numeric(s):
            n_num_disc += 1
        else:
            n_num_cont += 1
    else:
        if nunq == 2:
            n_dicot_nom += 1
        else:
            n_nominal_nao_dicot += 1

n_dicot_total = n_dicot_num + n_dicot_nom
n_total_entrada = df_final.shape[1] - 1
soma_exclusiva = n_num_cont + n_num_disc + n_dicot_num + n_dicot_nom + n_nominal_nao_dicot
print("Entrada:", n_total_entrada, "| Soma exclusiva:", soma_exclusiva)


# ============================================================
# CLASSE: tipo + quantidade de respostas
# ============================================================
y_series = df_final[y_col]
y_type = _tipo_atributo(y_series)
y_n_respostas = int(y_series.dropna().nunique())


# ============================================================
# RESUMO GERAL
# ============================================================
_section("Resumo geral")
display(HTML(_to_html(pd.DataFrame([
    {
        "Base original": f"{base_name}.csv",
        "Base final": out_path,
        "Instâncias finais": df_final.shape[0],
        "Numéricos contínuos": n_num_cont,
        "Numéricos discretos": n_num_disc,
        "Dicotômicos": n_dicot_total,
        "Nominais não-dicotômicos": n_nominal_nao_dicot,
        "Atributos de entrada": df_final.shape[1] - 1,
        "Classe (tipo)": y_type,
        "Classe (qtd respostas)": y_n_respostas,
    }
]))))

_section("Atributos removidos")
display(HTML(_to_html(attrs_removed_df)))

_section("Instâncias removidas (índices iniciam em 1)")
display(HTML(_to_html(inst_removed_df)))

_section("Atributos nominais (incluindo dicotômicos) restantes para codificação")
display(HTML(_to_html(
    nominal_df if not nominal_df.empty else pd.DataFrame({"Mensagem": ["Nenhum atributo nominal restante."]})
)))

_section("Balanceamento final da classe")
display(HTML(_to_html(balance_df)))

import os
import pandas as pd

def verificar_atributos_cardinalidade_1(pasta: str, sep=","):
    """
    Lê todos os CSVs de uma pasta e imprime quais possuem
    atributos com cardinalidade igual a 1.
    """
    arquivos = [f for f in os.listdir(pasta) if f.lower().endswith(".csv")]

    if not arquivos:
        print("Nenhum arquivo CSV encontrado na pasta.")
        return

    for arquivo in arquivos:
        caminho = os.path.join(pasta, arquivo)

        try:
            df = pd.read_csv(caminho, sep=sep)
        except Exception as e:
            print(f"[Erro] Não foi possível ler {arquivo}: {e}")
            continue

        atributos_card_1 = [
            col for col in df.columns
            if df[col].nunique(dropna=True) == 1
        ]

        if atributos_card_1:
            print(f"{arquivo}")
            # print("Atributos com cardinalidade = 1:")
            # for col in atributos_card_1:
            #     print(f"  - {col}")
        # else:

            # print(f"\nArquivo: {arquivo}")
            # print("Nenhum atributo com cardinalidade = 1.")

# EXEMPLO DE USO
pasta_csvs = "/content/drive/MyDrive/Dissertacao/BasesDissertacaoLimpa/Alta"
verificar_atributos_cardinalidade_1(pasta_csvs)