# -*- coding: utf-8 -*-
"""USADOCodOrdBin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GHPXi9un7Kb9vvowAe2MDAb_15DDB_B
"""

!pip install -q category_encoders

from google.colab import drive
drive.mount("/content/drive")



import os
from typing import Dict, List, Any

import numpy as np
import pandas as pd

from IPython.display import display

import category_encoders as ce

base_path = "/content/drive/MyDrive/Dissertacao/EstudoCaso/Depressao_Limpa.csv"
sep = ","

df = pd.read_csv(base_path, sep=sep)

# CLASSE = ÚLTIMA COLUNA (NÃO MUDA)
y_col = df.columns[-1]

display(df.head())
print(f"Instâncias: {df.shape[0]} | Atributos: {df.shape[1]}")
print(f"Classe (y): {y_col}")

"""# **ATRIBUTOS NOMINAIS + OPÇÕES DE RESPOSTA**"""

def _is_nominal_series(s: pd.Series) -> bool:
    return (
        pd.api.types.is_object_dtype(s)
        or pd.api.types.is_categorical_dtype(s)
        or pd.api.types.is_bool_dtype(s)
    )

def _sorted_unique_values(s: pd.Series, max_show: int = 80) -> List[Any]:
    vals = s.dropna().unique().tolist()
    try:
        vals = sorted(vals)
    except Exception:
        pass
    return vals if len(vals) <= max_show else (vals[:max_show] + ["..."])

nominal_cols = [c for c in df.columns if _is_nominal_series(df[c])]

rows = []
for c in nominal_cols:
    rows.append({
        "atributo": c,
        "niveis_distintos_(sem_NA)": int(df[c].nunique(dropna=True)),
        "inclui_NA": bool(df[c].isna().any()),
        "opcoes_(amostra/ordenado)": _sorted_unique_values(df[c], max_show=80),
        "eh_classe": (c == y_col),
    })

nominal_info = pd.DataFrame(rows).sort_values(
    by=["eh_classe", "niveis_distintos_(sem_NA)", "atributo"],
    ascending=[False, False, True]
)

display(nominal_info)

"""# **BINÁRIO (0/1) — CATEGORY_ENCODERS**"""

binary_mapping: Dict[str, Dict[Any, int]] = {

    # "Gender": {"Female": 0, "Male": 1},
    # "gender": {"F": 0, "M": 1},
    # "https": {"no": 0, "yes": 1},
    # "label": {"bad": 0, "good": 1},
    "Atendimento_psicológico_A_T1": {"não": 0, "sim": 1,"0":0},
    "Seus_pais_T1": {"separados/divorciados": 0, "juntos": 1},
    "Sexo_A": {"feminino": 0, "Masculino": 1},
    "CDI_Soma": {"Baixa": 0, "Alta": 1},




    # "marital_status": {"S": 0, "M": 1},

    # "claim_status": {"Rejected": 0, "Approved": 1},
    # "document_submission_mode": {"By_Hospital": 0, "By_Patient": 1},
    # "document_status": {"Incomplete": 0, "Complete": 1},
    # "admission_type": {"Planned": 0, "Emergency": 1},

    # "active_treatment_flag": {False: 0, True: 1},
    # "disclosure_of_material_fact": {False: 0, True: 1},
    # "disease_sub_limit_applies": {False: 0, True: 1},
    # "disease_sub_limit_capped": {False: 0, True: 1},
    # "fraud_indicator": {False: 0, True: 1},
    # "free_look_cancellation": {False: 0, True: 1},
    # "investigation_triggered": {False: 0, True: 1},
    # "is_modern_treatment": {False: 0, True: 1},

    # "gender": {"Female": 0, "Male": 1},
    # "hospitalization_type": {"Non_Network": 0, "Network": 1},

    # "is_senior_citizen": {False: 0, True: 1},
    # "ped_waiting_period_served": {False: 0, True: 1},
    # "portability_status": {False: 0, True: 1},
    # "provider_blacklist_flag": {False: 0, True: 1},
    # "specific_disease_waiting_period_served": {False: 0, True: 1},
    # "sum_insured_enhanced": {False: 0, True: 1},

    # "treatment_system": {"Allopathy": 0, "AYUSH": 1},

    # "zone_mismatch": {False: 0, True: 1},


    # "Result": {"No": 0, "Yes": 1},
    # "AfraidBadHappening": {"No": 0, "Yes": 1},
    # "Bored": {"No": 0, "Yes": 1},
    # "ConsiderWorthless": {"No": 0, "Yes": 1},
    # "CryMostOfTheTime": {"No": 0, "Yes": 1},
    # "DroppedActivities": {"No": 0, "Yes": 1},
    # "FeelEnergy": {"No": 0, "Yes": 1},
    # "FeelHelpless": {"No": 0, "Yes": 1},
    # "FeelLifeEmpty": {"No": 0, "Yes": 1},
    # "FeelingReduceAppetiteAndLosingWeight": {"No": 0, "Yes": 1},
    # "HopefulAboutFuture": {"No": 0, "Yes": 1},
    # "MemoryLoss": {"No": 0, "Yes": 1},
    # "OthersWouldBetterYouDied": {"No": 0, "Yes": 1},
    # "PeopleBetterThanYou": {"No": 0, "Yes": 1},
    # "PreferStayHome": {"No": 0, "Yes": 1},
    # "SatisfiedLife": {"No": 0, "Yes": 1},
    # "SituationHopeless": {"No": 0, "Yes": 1},
    # "SpendTimeHappily": {"No": 0, "Yes": 1},
    # "Result": {"No": 0, "Yes": 1},
    # "Battery_Backup_Status": {"Unavailable": 0, "Available": 1},


}

# Política para valores fora do mapeamento:
# - "error": interrompe
# - "nan": vira NaN
unknown_binary_policy = "error"  # "error" | "nan"

df_enc = df.copy()

for col, mp in binary_mapping.items():
    if col not in df_enc.columns:
        raise KeyError(f"[binário] Coluna não encontrada: {col}")

    # valida se o mapeamento tem exatamente {0,1}
    vals = sorted(set(mp.values()))
    if vals != [0, 1]:
        raise ValueError(f"[binário] {col}: mapping deve ter exatamente valores 0 e 1. Recebido: {vals}")

    observed = set(df_enc[col].dropna().unique().tolist())
    mapped = set(mp.keys())
    unknown_vals = observed - mapped

    if unknown_vals and unknown_binary_policy == "error":
        raise ValueError(f"[binário] {col}: valores não mapeados: {sorted(list(unknown_vals))}")

    df_enc[col] = df_enc[col].map(mp)  # desconhecidos -> NaN
    df_enc[col] = df_enc[col].astype("float")  # preserva NaN

print("Atributos binários codificados:", list(binary_mapping.keys()))
display(df_enc.head())

"""# **CODIFICAÇÃO ORDINAL**"""

ordinal_mapping = [
    # {'col': 'FeelBadAndGuilty', 'mapping': {'Not at All': 1, 'Sometimes': 2, 'Most Of The Time': 3, 'All The Time': 4}},
    # {'col': 'AvoidingSocialGatherings', 'mapping': {'Not at All': 1, 'Sometimes': 2, 'Most Of The Time': 3}},
    # {'col': 'SleepWell', 'mapping': {'Not at All': 1, 'Sometimes': 2, 'Most Of The Time': 3}},
    #  {'col': 'Day_of_Week', 'mapping': {'Sunday': 1, 'Monday': 2, 'Tuesday': 3,'Wednesday' :4, 'Thursday': 5, 'Friday':6, 'Saturday':7}},
    # #  {'col': 'Criticality_Level', 'mapping': {'Critical': 1, 'Low': 2, 'Medium': 3, 'High': 4}},
    #   {'col': 'avg. yearly_income', 'mapping': {'$10K - $30K':1 ,'$30K - $50K': 2,'$50K - $70K': 3,'$70K - $90K': 4,'$90K - $110K': 5, '$110K - $130K': 6,'$130K - $150K': 7,'$150K +':8}},
    #   {'col': 'member_card', 'mapping': {'Normal': 1, 'Bronze': 2, 'Golden': 3, 'Silver': 4}},
    #   {'col': 'education', 'mapping': {  "Partial High School": 1,
    # "High School Degree": 2,
    # "Partial College": 3,
    # "Bachelors Degree": 4,
    # "Graduate Degree": 5}},
    {'col': 'Escol_M', 'mapping': {
    'não sabe': 0,
    'Não estudou': 1,
    'Ensino Fundamental Incompleto': 2,
    'Ensino fundamental Completo': 3,
    'Ensino médio incompleto': 4,
    'Ensino médio completo': 5,
    'Superior incompleto': 6,
    'Superior completo': 7
}},

{'col': 'Escol_P', 'mapping': {
    'não sabe': 0,
    'Não estudou': 1,
    'Ensino Fundamental Incompleto': 2,
    'Ensino fundamental Completo': 3,
    'Ensino médio incompleto': 4,
    'Ensino médio completo': 5,
    'Superior incompleto': 6,
    'Superior completo': 7
}},



]

ordinal_cols = [m["col"] for m in ordinal_mapping]

# Política para valores fora do mapeamento ordinal:
# - handle_unknown='error'  -> interrompe
# - handle_unknown='value'  -> usa unknown_value (aqui: np.nan)
unknown_ordinal_policy = "error"  # "error" | "nan"

if ordinal_mapping:
    if unknown_ordinal_policy == "error":
        ord_enc = ce.OrdinalEncoder(
            mapping=ordinal_mapping,
            handle_unknown="error",
            handle_missing="return_nan",
        )
    elif unknown_ordinal_policy == "nan":
        ord_enc = ce.OrdinalEncoder(
            mapping=ordinal_mapping,
            handle_unknown="value",
            handle_missing="return_nan",
        )
        # category_encoders usa -1 por padrão em alguns casos; aqui garantimos NaN depois.
    else:
        raise ValueError(f"[ordinal] unknown_ordinal_policy inválida: {unknown_ordinal_policy}")

    df_enc = ord_enc.fit_transform(df_enc)

    # Se policy == "nan", força qualquer valor < 0 (desconhecido) para NaN
    if unknown_ordinal_policy == "nan":
        for col in ordinal_cols:
            if col in df_enc.columns:
                df_enc[col] = df_enc[col].where(df_enc[col] >= 0, np.nan)

print("Atributos ordinais codificados:", ordinal_cols)
display(df_enc.head())

"""# **SALVAR CSV FINAL**"""

out_dir = "/content/drive/MyDrive/Dissertacao/EstudoCaso"
os.makedirs(out_dir, exist_ok=True)

base_name = os.path.splitext(os.path.basename(base_path))[0]
out_path = os.path.join(out_dir, f"{base_name}.csv")

df_enc.to_csv(out_path, index=False, sep=",")

print("Arquivo salvo em:")
print(out_path)