# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBYLVDUe_zqiwsEwSlYpCa8Bnh3fGSnR

from google.colab import drive
drive.mount('/content/drive')

# Benchmark de codificadores categóricos (Parte 1 — geração de artefatos)

- Split **estratificado 80:20** e salvamento de `train.csv` / `test.csv`.
- **K-Fold (k=5)** apenas no treino.
- **Codificação dentro da dobra**: `fit` no `treino_fold` e `transform` no `val_fold`.
- Modelos: **Decision Tree, Random Forest, MLP, SVM, XGBoost** (defaults).
- Salvamento por base: métricas (CSV), tempos (CSV), dados para testes estatísticos futuros (CSV), mapeamentos (CSV), modelos finais `.joblib` (encoder + modelo).

> Este notebook **não** calcula SHAP e **não** executa testes estatísticos.
"""

# ==========================
# CONFIGURAÇÃO (AJUSTE AO EXECUTAR)
# ==========================
# Pasta com os CSVs de entrada (cada arquivo = uma base)
INPUT_DIR = "/home/977824/DISSERTACAO/Alta/Alta"

# Pasta de saída (será criado: OUT_DIR/NOME_DA_BASE/)
OUT_DIR = r"\home\977824\DISSERTACAO\Alta\Alta\Resultados"

# Separador do CSV
CSV_SEP = ","

# Coluna alvo (classe binária já codificada)
# - None => usa a ÚLTIMA coluna do CSV
# - ou defina o nome: "target"
TARGET_COL = None

# Split treino/teste
TEST_SIZE = 0.2
RANDOM_STATE = 42
SHUFFLE = True

# Validação cruzada (apenas no treino)
N_SPLITS = 5

# Regra de hashing (limiar de cardinalidade)
HASH_CARD_THRESHOLD = 100

#pip install category_encoders

# ==========================
# IMPORTS
# ==========================
import os
import glob
import time
import json
import datetime
import warnings
import importlib
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import precision_score, recall_score, f1_score

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC

import joblib

# dependências exigidas pelo experimento
for mod in ["category_encoders", "xgboost"]:
    try:
        importlib.import_module(mod)
    except ImportError as e:
        raise ImportError(f"Módulo ausente: {mod}. Instale antes de executar.") from e

import category_encoders as ce
from xgboost import XGBClassifier

warnings.filterwarnings("ignore")

# ==========================
# UTILITÁRIOS
# ==========================
def list_csv_files(input_dir: str) -> List[str]:
    files = sorted(glob.glob(os.path.join(input_dir, "*.csv")))
    return [f for f in files if os.path.isfile(f)]

def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)

def dataset_name_from_path(path: str) -> str:
    base = os.path.basename(path)
    return os.path.splitext(base)[0]

def split_X_y(df: pd.DataFrame, target_col: Optional[str]) -> Tuple[pd.DataFrame, pd.Series, str]:
    if target_col is None:
        target_col = df.columns[-1]
    if target_col not in df.columns:
        raise ValueError(f"TARGET_COL='{target_col}' não existe no CSV.")
    X = df.drop(columns=[target_col]).copy()
    y = df[target_col].copy()
    return X, y, target_col

def get_categorical_cols(X: pd.DataFrame) -> List[str]:
    # Regra (A): apenas colunas object/category
    return list(X.select_dtypes(include=["object", "category"]).columns)

def compute_cardinalities(X: pd.DataFrame, cat_cols: List[str]) -> Dict[str, int]:
    return {c: int(X[c].nunique(dropna=True)) for c in cat_cols}

def metric_triplet(y_true, y_pred) -> Tuple[float, float, float]:
    p = precision_score(y_true, y_pred, zero_division=0)
    r = recall_score(y_true, y_pred, zero_division=0)
    f = f1_score(y_true, y_pred, zero_division=0)
    return p, r, f

def to_numpy_matrix(X_enc) -> np.ndarray:
    if isinstance(X_enc, pd.DataFrame):
        return X_enc.to_numpy()
    if hasattr(X_enc, "toarray"):
        return X_enc.toarray()
    return np.asarray(X_enc)

def save_csv(df: pd.DataFrame, path: str) -> None:
    df.to_csv(path, index=False)

def safe_mode(series: pd.Series):
    m = series.mode(dropna=True)
    return m.iloc[0] if len(m) > 0 else np.nan

def make_baseline_row(X: pd.DataFrame) -> pd.DataFrame:
    baseline = {}
    for col in X.columns:
        s = X[col]
        if pd.api.types.is_numeric_dtype(s):
            baseline[col] = 0
        else:
            baseline[col] = safe_mode(s)
    return pd.DataFrame([baseline])

def now_iso() -> str:
    return datetime.datetime.now().isoformat(timespec="seconds")

import hashlib

def _hash_bucket(token: str, algo: str, n_buckets: int) -> int:
    b = token.encode("utf-8", errors="ignore")
    if algo == "md5":
        h = hashlib.md5(b).digest()
    elif algo == "sha256":
        h = hashlib.sha256(b).digest()
    else:
        raise ValueError("algo deve ser 'md5' ou 'sha256'")
    return int.from_bytes(h, byteorder="big", signed=False) % n_buckets

def _as_token(val) -> str:
    if pd.isna(val):
        return "nan"
    return str(val)

class HashGroupedEncoder(BaseEstimator, TransformerMixin):
    """Todas as colunas categóricas contribuem para o mesmo vetor final (n_components)."""
    def __init__(self, cols: List[str], algo: str = "md5", n_components: int = 8):
        self.cols = list(cols)
        self.algo = algo
        self.n_components = int(n_components)

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = pd.DataFrame(X).copy()
        n = len(X)
        out = np.zeros((n, self.n_components), dtype=np.float64)
        for i in range(n):
            for col in self.cols:
                token = f"{col}={_as_token(X.iloc[i][col])}"
                j = _hash_bucket(token, self.algo, self.n_components)
                out[i, j] += 1.0
        colnames = [f"COL_{k+1}" for k in range(self.n_components)]
        return pd.DataFrame(out, columns=colnames, index=X.index)

class HashSeparateEncoder(BaseEstimator, TransformerMixin):
    """Cada coluna gera seu próprio vetor (n_components) e depois concatena."""
    def __init__(self, cols: List[str], algo: str = "md5", n_components: int = 8):
        self.cols = list(cols)
        self.algo = algo
        self.n_components = int(n_components)

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = pd.DataFrame(X).copy()
        n = len(X)
        blocks = []
        for col in self.cols:
            out = np.zeros((n, self.n_components), dtype=np.float64)
            for i in range(n):
                token = f"{col}={_as_token(X.iloc[i][col])}"
                j = _hash_bucket(token, self.algo, self.n_components)
                out[i, j] += 1.0
            blocks.append(out)
        mat = np.concatenate(blocks, axis=1) if blocks else np.zeros((n, 0), dtype=np.float64)
        colnames = [f"COL_{k+1}" for k in range(mat.shape[1])]
        return pd.DataFrame(mat, columns=colnames, index=X.index)

class HashMixedGroupedEncoder(BaseEstimator, TransformerMixin):
    """Mista (agrupada): cols com card < threshold usam n_low; cols com card >= threshold usam n_high.
    Saída = concatenação [parte_low (n_low), parte_high (n_high)] com tamanhos FIXOS.
    """
    def __init__(self, cols: List[str], algo: str = "md5", threshold: int = 100, n_low: int = 8, n_high: int = 32):
        self.cols = list(cols)
        self.algo = algo
        self.threshold = int(threshold)
        self.n_low = int(n_low)
        self.n_high = int(n_high)
        self.low_cols_ = []
        self.high_cols_ = []

    def fit(self, X, y=None):
        X = pd.DataFrame(X)
        cards = {c: int(X[c].nunique(dropna=True)) for c in self.cols}
        self.low_cols_ = [c for c in self.cols if cards.get(c, 0) < self.threshold]
        self.high_cols_ = [c for c in self.cols if cards.get(c, 0) >= self.threshold]
        return self

    def transform(self, X):
        X = pd.DataFrame(X).copy()
        n = len(X)
        low = np.zeros((n, self.n_low), dtype=np.float64)
        high = np.zeros((n, self.n_high), dtype=np.float64)
        for i in range(n):
            for col in self.low_cols_:
                token = f"{col}={_as_token(X.iloc[i][col])}"
                j = _hash_bucket(token, self.algo, self.n_low)
                low[i, j] += 1.0
            for col in self.high_cols_:
                token = f"{col}={_as_token(X.iloc[i][col])}"
                j = _hash_bucket(token, self.algo, self.n_high)
                high[i, j] += 1.0
        mat = np.concatenate([low, high], axis=1)
        colnames = [f"COL_{k+1}" for k in range(mat.shape[1])]
        return pd.DataFrame(mat, columns=colnames, index=X.index)

# ==========================
# ENCODERS (defaults, exceto hashing) + MODELOS (defaults)
# ==========================
@dataclass(frozen=True)
class EncoderSpec:
    name: str
    kind: str  # 'unsupervised' | 'supervised'
    builder: callable  # (cat_cols) -> encoder

def _make_onehot_ct(cat_cols: List[str], drop: Optional[str]) -> ColumnTransformer:
    # handle_unknown='ignore' por exigência do experimento
    # saída densa para compatibilidade com MLP/SVM
    try:
        ohe = OneHotEncoder(handle_unknown="ignore", drop=drop, sparse_output=False)
    except TypeError:
        ohe = OneHotEncoder(handle_unknown="ignore", drop=drop, sparse=False)
    return ColumnTransformer(
        transformers=[("cat", ohe, cat_cols)],
        remainder="passthrough",
    )

def build_encoder_specs(cat_cols: List[str], X_train: pd.DataFrame, card_threshold: int) -> List[EncoderSpec]:
    cards = compute_cardinalities(X_train, cat_cols)
    all_lt = all(cards[c] < card_threshold for c in cat_cols)

    specs: List[EncoderSpec] = []

    # Não supervisionados
    specs.append(EncoderSpec("onehot", "unsupervised", lambda cc: _make_onehot_ct(cc, drop=None)))
    specs.append(EncoderSpec("dummy",  "unsupervised", lambda cc: _make_onehot_ct(cc, drop="first")))
    specs.append(EncoderSpec("count",     "unsupervised", lambda cc: ce.CountEncoder(cols=cc)))
    specs.append(EncoderSpec("frequency", "unsupervised", lambda cc: ce.CountEncoder(cols=cc, normalize=True)))
    specs.append(EncoderSpec("ordinal",   "unsupervised", lambda cc: ce.OrdinalEncoder(cols=cc)))
    specs.append(EncoderSpec("helmert",   "unsupervised", lambda cc: ce.HelmertEncoder(cols=cc)))
    specs.append(EncoderSpec("binary",    "unsupervised", lambda cc: ce.BinaryEncoder(cols=cc)))

    # Hashing (14 nomes possíveis; por base executa subconjunto)
    if all_lt:
        for algo in ["md5", "sha256"]:
            specs.append(EncoderSpec(f"hash_{algo}_8_grouped_alllt100", "unsupervised",
                                     lambda cc, a=algo: HashGroupedEncoder(cols=cc, algo=a, n_components=8)))
            specs.append(EncoderSpec(f"hash_{algo}_8_separate_alllt100", "unsupervised",
                                     lambda cc, a=algo: HashSeparateEncoder(cols=cc, algo=a, n_components=8)))
    else:
        for algo in ["md5", "sha256"]:
            specs.append(EncoderSpec(f"hash_{algo}_8_grouped_anyge100", "unsupervised",
                                     lambda cc, a=algo: HashGroupedEncoder(cols=cc, algo=a, n_components=8)))
            specs.append(EncoderSpec(f"hash_{algo}_8_separate_anyge100", "unsupervised",
                                     lambda cc, a=algo: HashSeparateEncoder(cols=cc, algo=a, n_components=8)))
            specs.append(EncoderSpec(f"hash_{algo}_32_grouped_anyge100", "unsupervised",
                                     lambda cc, a=algo: HashGroupedEncoder(cols=cc, algo=a, n_components=32)))
            specs.append(EncoderSpec(f"hash_{algo}_32_separate_anyge100", "unsupervised",
                                     lambda cc, a=algo: HashSeparateEncoder(cols=cc, algo=a, n_components=32)))
            specs.append(EncoderSpec(f"hash_{algo}_mixed_grouped_anyge100", "unsupervised",
                                     lambda cc, a=algo: HashMixedGroupedEncoder(cols=cc, algo=a,
                                                                              threshold=card_threshold,
                                                                              n_low=8, n_high=32)))

    # Supervisionados
    specs.append(EncoderSpec("catboost",    "supervised", lambda cc: ce.CatBoostEncoder(cols=cc)))
    specs.append(EncoderSpec("target",      "supervised", lambda cc: ce.TargetEncoder(cols=cc)))
    specs.append(EncoderSpec("leaveoneout", "supervised", lambda cc: ce.LeaveOneOutEncoder(cols=cc)))

    return specs

@dataclass(frozen=True)
class ModelSpec:
    name: str
    builder: callable

MODEL_SPECS = [
    ModelSpec("dtree", lambda: DecisionTreeClassifier()),
    ModelSpec("rf",    lambda: RandomForestClassifier()),
    ModelSpec("mlp",   lambda: MLPClassifier()),
    ModelSpec("svm",   lambda: SVC()),
    ModelSpec("xgb",   lambda: XGBClassifier()),
]

# ==========================
# MAPEAMENTOS (train/test) — SEM refazer fit no teste
# ==========================
def _is_sklearn_ohe_ct(encoder) -> bool:
    return isinstance(encoder, ColumnTransformer) and hasattr(encoder, "named_transformers_") and ("cat" in encoder.named_transformers_)

def _extract_ohe(encoder: ColumnTransformer) -> OneHotEncoder:
    return encoder.named_transformers_["cat"]

def mapping_onehot_or_dummy_train_test(
    encoder: ColumnTransformer,
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    cat_cols: List[str],
    encoder_name: str,
    out_dir: str,
) -> None:
    ohe = _extract_ohe(encoder)
    learned = {col: list(ohe.categories_[i]) for i, col in enumerate(cat_cols)}

    dropped = {}
    try:
        drop_idx = ohe.drop_idx_
        if drop_idx is not None:
            for i, col in enumerate(cat_cols):
                idx = drop_idx[i]
                if idx is not None and idx >= 0:
                    dropped[col] = learned[col][idx]
    except Exception:
        dropped = {}

    def _build(split_name: str, X: pd.DataFrame) -> pd.DataFrame:
        rows = []
        for col in cat_cols:
            seen = pd.Series(X[col]).drop_duplicates().tolist()
            for cat in seen:
                if cat in learned[col]:
                    if col in dropped and cat == dropped[col]:
                        rows.append({
                            "split": split_name,
                            "encoder": encoder_name,
                            "feature": col,
                            "category": cat,
                            "encoded_feature": "",
                            "encoded_value": "",
                            "note": "dropped_reference"
                        })
                    else:
                        # nome compatível com OneHotEncoder (sem prefixo do ColumnTransformer)
                        feat_name = f"{col}_{cat}"
                        # no output completo do ColumnTransformer, normalmente vira: cat__<feat_name>
                        rows.append({
                            "split": split_name,
                            "encoder": encoder_name,
                            "feature": col,
                            "category": cat,
                            "encoded_feature": f"cat__{feat_name}",
                            "encoded_value": 1,
                            "note": ""
                        })
                else:
                    rows.append({
                        "split": split_name,
                        "encoder": encoder_name,
                        "feature": col,
                        "category": cat,
                        "encoded_feature": "",
                        "encoded_value": "",
                        "note": "unknown_in_train"  # handle_unknown='ignore' => vetor de zeros
                    })
        return pd.DataFrame(rows)

    save_csv(_build("train", X_train), os.path.join(out_dir, f"mapping_{encoder_name}_train.csv"))
    save_csv(_build("test",  X_test),  os.path.join(out_dir, f"mapping_{encoder_name}_test.csv"))

def _infer_feature_output_cols(encoded_cols: List[str], feature: str) -> List[str]:
    # Prioridade: coluna única com mesmo nome (ex.: count/ordinal/target/catboost/loo)
    if feature in encoded_cols:
        return [feature]
    # Expansões típicas (binary/helmert): feature_0, feature_1, ...
    pref = feature + "_"
    return [c for c in encoded_cols if c.startswith(pref)]

def mapping_category_encoders_train_test(
    encoder,
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    cat_cols: List[str],
    encoder_name: str,
    out_dir: str,
) -> None:
    baseline = make_baseline_row(X_train)
    enc_baseline = encoder.transform(baseline)
    if not isinstance(enc_baseline, pd.DataFrame):
        enc_baseline = pd.DataFrame(enc_baseline)
    encoded_cols = list(enc_baseline.columns)

    def _build(split_name: str, X: pd.DataFrame) -> pd.DataFrame:
        rows = []
        for feat in cat_cols:
            out_cols = _infer_feature_output_cols(encoded_cols, feat)
            cats = pd.Series(X[feat]).drop_duplicates().tolist()
            for cat in cats:
                tmp = baseline.copy()
                tmp.loc[tmp.index[0], feat] = cat
                enc_tmp = encoder.transform(tmp)
                if not isinstance(enc_tmp, pd.DataFrame):
                    enc_tmp = pd.DataFrame(enc_tmp, columns=encoded_cols)
                for oc in out_cols:
                    rows.append({
                        "split": split_name,
                        "encoder": encoder_name,
                        "feature": feat,
                        "category": cat,
                        "encoded_feature": oc,
                        "encoded_value": enc_tmp.loc[enc_tmp.index[0], oc],
                    })
        return pd.DataFrame(rows)

    save_csv(_build("train", X_train), os.path.join(out_dir, f"mapping_{encoder_name}_train.csv"))
    save_csv(_build("test",  X_test),  os.path.join(out_dir, f"mapping_{encoder_name}_test.csv"))

def mapping_hash_train_test(
    encoder,
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    cat_cols: List[str],
    encoder_name: str,
    out_dir: str,
) -> None:
    # train: combinações distintas + freq
    train_cats = X_train[cat_cols].copy()
    train_freq = train_cats.value_counts(dropna=False).reset_index(name="freq_train")
    train_vec  = encoder.transform(train_freq[cat_cols])

    # test: combinações distintas + freq
    test_cats = X_test[cat_cols].copy()
    test_freq = test_cats.value_counts(dropna=False).reset_index(name="freq_test")
    test_vec  = encoder.transform(test_freq[cat_cols])

    df_train = pd.concat([train_freq[cat_cols], train_vec.reset_index(drop=True), train_freq[["freq_train"]]], axis=1)
    df_test  = pd.concat([test_freq[cat_cols],  test_vec.reset_index(drop=True),  test_freq[["freq_test"]]], axis=1)

    save_csv(df_train, os.path.join(out_dir, f"mapping_{encoder_name}_train.csv"))
    save_csv(df_test,  os.path.join(out_dir, f"mapping_{encoder_name}_test.csv"))

# ==========================
# EXECUÇÃO PRINCIPAL (por base)
# ==========================
def run_for_one_dataset(csv_path: str) -> None:
    ds_name = dataset_name_from_path(csv_path)
    ds_out = os.path.join(OUT_DIR, ds_name)
    ensure_dir(ds_out)

    # 1) Ler base e separar X/y
    df = pd.read_csv(csv_path, sep=CSV_SEP)
    X, y, y_col = split_X_y(df, TARGET_COL)

    # 2) Split 80:20 e salvamento
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        shuffle=SHUFFLE,
        stratify=y,
    )

    save_csv(pd.concat([X_train.reset_index(drop=True), y_train.reset_index(drop=True)], axis=1),
             os.path.join(ds_out, "train.csv"))
    save_csv(pd.concat([X_test.reset_index(drop=True), y_test.reset_index(drop=True)], axis=1),
             os.path.join(ds_out, "test.csv"))

    # 3) Colunas categóricas (object/category)
    cat_cols = get_categorical_cols(X_train)
    if len(cat_cols) == 0:
        raise ValueError(f"Base '{ds_name}': nenhuma coluna object/category encontrada para codificar.")

    # 4) Encoders (hashing decidido com base no TREINO)
    encoder_specs = build_encoder_specs(cat_cols, X_train, card_threshold=HASH_CARD_THRESHOLD)

    # 5) Validação cruzada (apenas no treino)
    skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)

    metrics_rows = []
    times_rows = []
    stats_rows = []  # pronto para testes estatísticos posteriores (por dobra; tipicamente usa-se cv_val)
    dims_rows = [] 

    fold_id = 0
    for tr_idx, va_idx in skf.split(X_train, y_train):
        fold_id += 1
        X_tr = X_train.iloc[tr_idx].reset_index(drop=True)
        y_tr = y_train.iloc[tr_idx].reset_index(drop=True)
        X_va = X_train.iloc[va_idx].reset_index(drop=True)
        y_va = y_train.iloc[va_idx].reset_index(drop=True)

        for enc_spec in encoder_specs:
            encoder = enc_spec.builder(cat_cols)

            # (4) Fit apenas no treino_fold; transform no treino_fold e no val_fold
            t0 = time.perf_counter()
            if enc_spec.kind == "supervised":
                encoder.fit(X_tr, y_tr)
            else:
                encoder.fit(X_tr)
            X_tr_enc = encoder.transform(X_tr)
            X_va_enc = encoder.transform(X_va)
            t1 = time.perf_counter()

            times_rows.append({
                "dataset": ds_name,
                "stage": "cv",
                "fold": fold_id,
                "encoder": enc_spec.name,
                "algorithm": "",
                "what": "encoding_fit_transform",
                "seconds": (t1 - t0),
            })

            X_tr_mat = to_numpy_matrix(X_tr_enc)
            X_va_mat = to_numpy_matrix(X_va_enc)

                        # ---- DIMENSIONALIDADE (CV) ----
            dims_rows.append({
                "dataset": ds_name,
                "stage": "cv",
                "fold": fold_id,
                "encoder": enc_spec.name,
                "split": "train_fold",
                "n_features_before": int(X_tr.shape[1]),
                "n_features_after": int(X_tr_mat.shape[1]),
            })
            dims_rows.append({
                "dataset": ds_name,
                "stage": "cv",
                "fold": fold_id,
                "encoder": enc_spec.name,
                "split": "val_fold",
                "n_features_before": int(X_va.shape[1]),
                "n_features_after": int(X_va_mat.shape[1]),
            })

            for model_spec in MODEL_SPECS:
                model = model_spec.builder()

                t2 = time.perf_counter()
                model.fit(X_tr_mat, y_tr)
                t3 = time.perf_counter()

                times_rows.append({
                    "dataset": ds_name,
                    "stage": "cv",
                    "fold": fold_id,
                    "encoder": enc_spec.name,
                    "algorithm": model_spec.name,
                    "what": "model_fit",
                    "seconds": (t3 - t2),
                })

                # métricas no treino_fold
                yhat_tr = model.predict(X_tr_mat)
                p_tr, r_tr, f_tr = metric_triplet(y_tr, yhat_tr)
                metrics_rows.append({
                    "dataset": ds_name,
                    "encoder": enc_spec.name,
                    "algorithm": model_spec.name,
                    "stage": "cv_train",
                    "fold": fold_id,
                    "precision": p_tr,
                    "recall": r_tr,
                    "f1": f_tr,
                })

                # métricas no val_fold
                yhat_va = model.predict(X_va_mat)
                p_va, r_va, f_va = metric_triplet(y_va, yhat_va)
                metrics_rows.append({
                    "dataset": ds_name,
                    "encoder": enc_spec.name,
                    "algorithm": model_spec.name,
                    "stage": "cv_val",
                    "fold": fold_id,
                    "precision": p_va,
                    "recall": r_va,
                    "f1": f_va,
                })

                stats_rows.extend([
                    {"dataset": ds_name, "encoder": enc_spec.name, "algorithm": model_spec.name, "fold": fold_id, "stage": "cv_val", "metric": "precision", "value": p_va},
                    {"dataset": ds_name, "encoder": enc_spec.name, "algorithm": model_spec.name, "fold": fold_id, "stage": "cv_val", "metric": "recall", "value": r_va},
                    {"dataset": ds_name, "encoder": enc_spec.name, "algorithm": model_spec.name, "fold": fold_id, "stage": "cv_val", "metric": "f1", "value": f_va},
                ])

    # 6) Treinamento final e teste (fora do CV)
    for enc_spec in encoder_specs:
        encoder_final = enc_spec.builder(cat_cols)

        t0 = time.perf_counter()
        if enc_spec.kind == "supervised":
            encoder_final.fit(X_train, y_train)
        else:
            encoder_final.fit(X_train)
        X_train_enc = encoder_final.transform(X_train)
        X_test_enc  = encoder_final.transform(X_test)
        t1 = time.perf_counter()

        times_rows.append({
            "dataset": ds_name,
            "stage": "final",
            "fold": "",
            "encoder": enc_spec.name,
            "algorithm": "",
            "what": "encoding_fit_transform",
            "seconds": (t1 - t0),
        })

        # mapeamentos para esta codificação (fit no treino inteiro; transform no teste sem refazer fit)
        if _is_sklearn_ohe_ct(encoder_final):
            mapping_onehot_or_dummy_train_test(encoder_final, X_train, X_test, cat_cols, enc_spec.name, ds_out)
        elif enc_spec.name.startswith("hash_"):
            mapping_hash_train_test(encoder_final, X_train, X_test, cat_cols, enc_spec.name, ds_out)
        else:
            mapping_category_encoders_train_test(encoder_final, X_train, X_test, cat_cols, enc_spec.name, ds_out)

        X_train_mat = to_numpy_matrix(X_train_enc)
        X_test_mat  = to_numpy_matrix(X_test_enc)

                # ---- DIMENSIONALIDADE (FINAL) ----
        dims_rows.append({
            "dataset": ds_name,
            "stage": "final",
            "fold": "",
            "encoder": enc_spec.name,
            "split": "train",
            "n_features_before": int(X_train.shape[1]),
            "n_features_after": int(X_train_mat.shape[1]),
        })
        dims_rows.append({
            "dataset": ds_name,
            "stage": "final",
            "fold": "",
            "encoder": enc_spec.name,
            "split": "test",
            "n_features_before": int(X_test.shape[1]),
            "n_features_after": int(X_test_mat.shape[1]),
        })

        for model_spec in MODEL_SPECS:
            model_final = model_spec.builder()

            t2 = time.perf_counter()
            model_final.fit(X_train_mat, y_train)
            t3 = time.perf_counter()

            times_rows.append({
                "dataset": ds_name,
                "stage": "final",
                "fold": "",
                "encoder": enc_spec.name,
                "algorithm": model_spec.name,
                "what": "model_fit",
                "seconds": (t3 - t2),
            })

            yhat_test = model_final.predict(X_test_mat)
            p_te, r_te, f_te = metric_triplet(y_test, yhat_test)
            metrics_rows.append({
                "dataset": ds_name,
                "encoder": enc_spec.name,
                "algorithm": model_spec.name,
                "stage": "test",
                "fold": "",
                "precision": p_te,
                "recall": r_te,
                "f1": f_te,
            })

            # Salvar pipeline completo (encoder + modelo) apenas do treinamento final
            pipe = Pipeline(steps=[("encoder", encoder_final), ("model", model_final)])
            joblib.dump(pipe, os.path.join(ds_out, f"model_{enc_spec.name}_{model_spec.name}.joblib"))
            print(f"{ds_name} | {model_spec.name} | {enc_spec.name}", flush=True)
    # 7) Salvar artefatos por base
    save_csv(pd.DataFrame(metrics_rows), os.path.join(ds_out, "metrics.csv"))
    save_csv(pd.DataFrame(times_rows),   os.path.join(ds_out, "times.csv"))
    save_csv(pd.DataFrame(stats_rows),   os.path.join(ds_out, "stats_ready.csv"))
    save_csv(pd.DataFrame(dims_rows),    os.path.join(ds_out, "dims.csv")) 

    with open(os.path.join(ds_out, "run_info.json"), "w", encoding="utf-8") as f:
        json.dump({
            "dataset": ds_name,
            "source_csv": csv_path,
            "target_col_used": y_col,
            "categorical_cols_encoded": cat_cols,
            "n_splits": N_SPLITS,
            "random_state": RANDOM_STATE,
            "created_at": now_iso(),
        }, f, ensure_ascii=False, indent=2)

def run_all() -> None:
    if not INPUT_DIR or not OUT_DIR:
        raise ValueError("Defina INPUT_DIR e OUT_DIR na célula de CONFIGURAÇÃO.")
    ensure_dir(OUT_DIR)

    csv_files = list_csv_files(INPUT_DIR)
    if len(csv_files) == 0:
        raise ValueError(f"Nenhum CSV encontrado em: {INPUT_DIR}")

    for csv_path in csv_files:
        run_for_one_dataset(csv_path)

    print("Concluído. Resultados em:", OUT_DIR)

# Execute:
run_all()

"""## Como usar

1. Salve este arquivo como `benchmark_encoders_parte1.ipynb`.
2. Abra no Jupyter/Colab.
3. Preencha `INPUT_DIR` e `OUT_DIR`.
4. Se necessário, defina `TARGET_COL` (ou deixe `None` para usar a última coluna).
5. Rode `run_all()`.

Estrutura por base em `OUT_DIR/NOME_DA_BASE/`:
- `train.csv`, `test.csv`
- `metrics.csv` (linhas: `cv_train`, `cv_val`, `test`)
- `times.csv` (tempo de codificação e de treino)
- `stats_ready.csv` (valores por dobra para testes posteriores)
- `mapping_<encoder>_train.csv` e `mapping_<encoder>_test.csv`
- `model_<encoder>_<algoritmo>.joblib`
- `run_info.json`

"""
